---
deployment:
  tasks:
  - export DEPLOYPATH=/home/user/public_html/
  - /bin/cp index.html $DEPLOYPATH
  - /bin/cp -R img/ $DEPLOYPATH/img
  - /bin/cp -R css/ $DEPLOYPATH/css
  - /bin/cp -R js/ $DEPLOYPATH/js
