---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ipharmacares/public_html/
    - export REPOPATH=/home/ipharmacares/repositories/img
     /bin cp /img/* $DEPLOYPATH  
    /bin/cp -r . $DEPLOYPATH.

